In [1]:
# dataset taken from https://jovian.ai/aakashns/02-linear-regression

import torch
import numpy as np

#Input Data
#(rainfalls, humidity, temp)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

#quantity of apples and oranges
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

inputs = torch.from_numpy(inputs)

targets = torch.from_numpy(targets)

w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)

def model(x):
    return x @ w.t() + b


def mse(t1,t2):
    diff = t1 - t2
    
    return torch.sum(diff * diff) / diff.numel()


    
for epoch in range(1000):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

preds = model(inputs)
loss = mse(preds, targets)

print(preds)
print(targets)
    
    

tensor([[ 58.3211,  69.2558],
        [ 78.9480, 110.5885],
        [124.2561, 112.0926],
        [ 24.3722,  32.5350],
        [ 94.9434, 138.8913]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [2]:
import torch
import torch.nn as nn
import numpy as np
from torch.utils.data import TensorDataset, DataLoader


inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs.dtype)

train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

batch_size = 5

train_dl = DataLoader(train_ds, batch_size, shuffle = True)

model = nn.Linear(3,2)

preds = model(inputs)

import torch.nn.functional as F
loss_fn = F.mse_loss

loss = loss_fn(model(inputs), targets)

opt = torch.optim.SGD(model.parameters(), lr = 1e-5)

def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()

fit(1000, model, loss_fn, opt, train_dl)
preds = model(inputs)
print(preds)
print(targets) 

torch.float32
tensor([[ 56.8871,  70.4616],
        [ 81.9606, 100.2820],
        [118.4836, 133.1526],
        [ 20.9032,  37.8333],
        [101.5867, 118.0928],
        [ 55.6417,  69.3762],
        [ 81.7968, 100.3403],
        [118.7721, 133.7299],
        [ 22.1487,  38.9187],
        [102.6684, 119.2366],
        [ 56.7233,  70.5199],
        [ 80.7151,  99.1966],
        [118.6474, 133.0942],
        [ 19.8216,  36.6895],
        [102.8322, 119.1782]], grad_fn=<AddmmBackward>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])
